# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a41204795dfea9ce46d7a099eb85f3e9cc9b04c33470e3e61bfd750b87a41a3c07cdb4ae75dfa63f485cc50ae8e6aa82e65c8af9067af7173cd996f32d35116f

test:
  secret_key_base: 6aa87a0a0221cb505491e47f7ee4f3fd0d62bb404a0fb27730746a8e6f7946c08dce97ff9be1d25c56e668441b6301c2120898e23097ba554f9b360730ac8789

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
